### PR TITLE
Executeable python file. 

### PR DESCRIPTION
**Pull request by XingwenZhang**
2016/11/13. This file just contains half of the origin files, but is executeable. The rest of the file is still on work. file operations are commentted out. Enviroment: Ubuntu, Python3. By: AngusZhang

### CODE REVIEW

**Comment by YoungZiyi** [comment]
great!

**Comment by xianhu** [comment]
你可以创建一个新文件，叫做python_base_executeable.py

**Comment by XingwenZhang** [comment]
Yep, I have created a new file named python_base_executable.py 
And it has finished the whole file.

**Comment by xianhu** [comment]
Thanks

**Pull request merged**
